INSERT INTO CASH_CARD(ID, AMOUNT, CARD_OWNER) VALUES (99, 123.45, 'sarah1');
INSERT INTO CASH_CARD(ID, AMOUNT, CARD_OWNER) VALUES (100, 1.00, 'sarah1');
INSERT INTO CASH_CARD(ID, AMOUNT, CARD_OWNER) VALUES (101, 150.00, 'sarah1');
INSERT INTO CASH_CARD(ID, AMOUNT, CARD_OWNER) VALUES (102, 200.00, 'kumar2');




INSERT INTO CASH_CARD_USER(USERNAME, PASSWORD, ROLES) VALUES ( 'sarah1', 'abc123', 'ROLE_OWNER,ROLE_USER' );
INSERT INTO CASH_CARD_USER(USERNAME, PASSWORD, ROLES) VALUES ( 'kumar2', 'xyz789', 'ROLE_OWNER,ROLE_USER' );
INSERT INTO CASH_CARD_USER(USERNAME, PASSWORD, ROLES) VALUES ( 'hank-owns-no-cards', 'qrs456', 'ROLE_USER' );
