INSERT INTO CASH_CARD(ID, AMOUNT, CARD_OWNER) VALUES (199, 123.45, 'sarah');
INSERT INTO CASH_CARD(ID, AMOUNT, CARD_OWNER) VALUES (200, 1.00, 'sarah');
INSERT INTO CASH_CARD(ID, AMOUNT, CARD_OWNER) VALUES (201, 150.00, 'sarah');
INSERT INTO CASH_CARD(ID, AMOUNT, CARD_OWNER) VALUES (202, 200.00, 'kumar');




INSERT INTO CASH_CARD_USER(USERNAME, PASSWORD, ROLES) VALUES ( 'sarah', 'abc123', 'ROLE_OWNER,ROLE_USER' );
INSERT INTO CASH_CARD_USER(USERNAME, PASSWORD, ROLES) VALUES ( 'kumar', 'xyz789', 'ROLE_OWNER,ROLE_USER' );
INSERT INTO CASH_CARD_USER(USERNAME, PASSWORD, ROLES) VALUES ( 'hanks', 'qrs456', 'ROLE_USER' );
